### ISSUE TITLE
Cannot import `aiopoke` module

### ISSUE THREAD

**Issue by CodePurble** [beastmatser/aiopokeapi#26]
Module import fails even after installing by running pip install aiopokeapi. I have even tried using Python venv, but it still does not work.

**To Reproduce**
1. Run `pip install aiopokeapi`
2. In Python shell, run `import aiopoke`

**Expected behavior**
Module must be imported.

**Screenshots**
![image](https://user-images.githubusercontent.com/49452779/179536735-aba2890f-227a-4cbe-9477-dd8b314c2667.png)

**Desktop:**
 - OS: Arch Linux
 - Python: 3.10.5

**Comment by beastmatser** [comment]
It should be fixed in version 0.1.4, so just try `pip install aiopokeapi` once more, if it doesn't work just let me know.

**Comment by CodePurble** [comment]
It works now, thank you for the prompt fix.
