### ISSUE TITLE
Incorrect typehint for Nature.increased_stat, Nature.decreased_stat

### ISSUE THREAD

**Issue by PikalaxALT** [beastmatser/aiopokeapi#58]
In `aiopoke.objects.resources.pokemon.nature.Nature`, attributes `increased_stat` and `decreased_stat` are typehinted as `Optional[MinimalResource["PokeathlonStat"]]` when they should be `Optional[MinimalResource["Stat"]]`. This issue misleads linters into thinking the return type from `await fetch()` is `PokeathlonStat` rather than `Stat`.

**Comment by beastmatser** [comment]
Thank you for bringing this to my attention. It should be fixed with 4dcea94cff33c158f579c39c7220c33cc4e8137a, make sure to update your version.
