### ISSUE TITLE
Possible bug: "TypeError: aiopoke.objects.resources.moves.move.ContestComboSets() argument after ** must be a mapping, not NoneType"

### ISSUE THREAD

**Issue by criiptico** [beastmatser/aiopokeapi#66]
**Describe the bug**
I try to iterate through a bunch of move id's which are keys stored in a dict (map). Then I use `moveData = await client.get_move(move)` to get the move's data and to print the move's power. My program only iterates through the dict once, displays the move's id and power, but it crashes the second time with an error.

**To Reproduce**
1. Store a pokemon's move id and name in a dictionary
2. Iterate through the dictionary and use the keys to search for a move's data using `get_move(move_id)`
3. See error

```
> Traceback (most recent call last):
>   File "/home/adrian/projects/poketype/prototype/old-main-aiopoke.py", line 121, in <module>
>     asyncio.run(main())
>   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
>     return future.result()
>   File "/home/adrian/projects/poketype/prototype/old-main-aiopoke.py", line 92, in main
>     await loadBaseDamage(opponentOne, opponentOneMoves)
>   File "/home/adrian/projects/poketype/prototype/old-main-aiopoke.py", line 65, in loadBaseDamage
>     moveData = await client.get_move(move)
>   File "/home/adrian/projects/virtualEnvironments/pokeTypeVenv/lib/python3.10/site-packages/aiopoke/utils/cache.py", line 27, in wrapper
>     obj: U = await coro(client, name_or_id)
>   File "/home/adrian/projects/virtualEnvironments/pokeTypeVenv/lib/python3.10/site-packages/aiopoke/aiopoke_client.py", line 193, in get_move
>     return Move(**data)
>   File "/home/adrian/projects/virtualEnvironments/pokeTypeVenv/lib/python3.10/site-packages/aiopoke/objects/resources/moves/move.py", line 87, in __init__
>     self.contest_combos = ContestComboSets(**contest_combos)
> TypeError: aiopoke.objects.resources.moves.move.ContestComboSets() argument after ** must be a mapping, not NoneType
```

**Expected behavior**
It's expected to retrieve the move's data, display the power, then repeat until the end of the dict is reached.

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
[Here](https://github.com/criiptico/poketype/blob/main/prototype/main-aiopoke.py) is the file from the repository with the project I'm working on. The problem is in the loadBaseDamage() function, lines 61 - 66.

I'm not sure what type of bug this is, but this is all I know about this error.

**Comment by beastmatser** [comment]
Should be fixed in 2b4f33b5d674249de2bd26ac7b9576d0825b1a5b, just make sure to retrieve the latest version from Github, so that the bug wont appear. Thanks for your contribution.
